---
include:
  - board: ergohaven
    shield: velvet_v3_left
    keymap: velvet_v3_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: velvet_v3_left_ruen-ergohaven-zmk
   
  - board: ergohaven
    shield: velvet_v3_ui_right
    keymap: velvet_v3_ui_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: velvet_v3_ui_right_ruen-ergohaven-zmk
  
  - board: ergohaven
    shield: settings_reset
    artifact-name: settings_reset-zmk
